export const API_VERSION = 'v1';

export const ISSUE_STATUSES = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
} as const;

export const ROLES = {
  CITIZEN: 'CITIZEN',
  MUNICIPALITY_EMPLOYEE: 'MUNICIPALITY_EMPLOYEE',
  MUNICIPALITY_MANAGER: 'MUNICIPALITY_MANAGER',
  NGO_REPRESENTATIVE: 'NGO_REPRESENTATIVE',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export * from './translations';

